apiVersion: v1
kind: Secret
metadata:
  name: book-review-secret
  namespace: book-review

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: my-secret-pw
  MYSQL_PASSWORD: admin123
  JWT_SECRET: local-development-secret